language: node_js
node_js:
  - "8"
cache:
  directories:
  - lambda/custom/node_modules
install:
  - npm install -g bespoken-tools
  - npm install codecov -g
  - cd lambda/custom && npm install && cd ../..
script:
  - bst test unit/test
  - codecov